load("CArray.js");
load("bubbleSort.js");
load("insertionSort.js");
load("selectionSort.js");
load("shellsort.js");
var nums = new CArray(10);
nums.setData();
print("Before Shellsort: \n");
print(nums.toString());
print("\nDuring Shellsort: \n");
nums.shellsort();
print("\nAfter Shellsort: \n");
print(nums.toString());
